apiVersion: v1
kind: Service
metadata:
  name: custom-nginx-service
  labels:
    - custom-nginx-label
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: release-name
